services:
  db:
    container_name: snailsoup_expenses_db
    image: postgres:15.4
    restart: no
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: expenses
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 2s
      timeout: 1s
      retries: 5
volumes:
  pgdata:
